// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcqlrgirykwhawuezgpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjcWxyZ2lyeWt3aGF3dWV6Z3B0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMzc2NTgsImV4cCI6MjA2MTcxMzY1OH0.4mI1mnYyzwRiXrL97YJBHPgCgslyrMwb2OaFoE-Sg2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);